services:
  windows:
    image: dockurr/windows
    container_name: windows
    environment:
      VERSION: "11l"
      KEYBOARD: "it-IT"
      REGION: "en-US"
      RAM_SIZE: "2G"
    devices:
      - /dev/kvm
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 5985:5985
      - 3389:3389/tcp
      - 3389:3389/udp
    volumes:
      - ./windows:/storage
      - ./testdata:/shared
    restart: unless-stopped
    stop_grace_period: 2m